name: Notify Deploy Repo

on:
  push:
    branches:
      - main

jobs:
  notify-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Repo Dispatch Event
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.DEPLOY_TRIGGER_TOKEN }}" \
            https://api.github.com/repos/LAB-University-of-Applied-Sciences/koppero/dispatches \
            -d '{"event_type":"submodule-updated"}'
